<?php

class FinishingSituation extends VV_Model
{
	
	function __construct()
	{
		parent::__construct();
		$this->table_name = FINISHING_SITUATION_DATA;
		
	}

	public function pdf_produce_finishing_situation($date_from,$date_to){
		/*$this->db->select("SUM(".FSD_SHEET.") AS ".FSD_SHEET.",SUM(".FSD_SHEETS.") AS ".FSD_SHEETS.",SUM(".FSD_SHEET_WASH_AGAIN.") AS ".FSD_SHEET_WASH_AGAIN.",SUM(".FSD_SHEET_BREAKING.") AS ".FSD_SHEET_BREAKING.",SUM(".FSD_SHEETS_2.") AS ".FSD_SHEETS_2.",SUM(".FSD_TOP.") AS ".FSD_TOP.",SUM(".FSD_TOP_STAINS.") AS ".FSD_TOP_STAINS.",SUM(".FSD_TOP_WASH_AGAIN.") AS ".FSD_TOP_WASH_AGAIN.",SUM(".FSD_TOP_BREAK.") AS ".FSD_TOP_BREAK.",SUM(".FSD_TOP_2.") AS ".FSD_TOP_2.",SUM(".FSD_DUVE.") AS ".FSD_DUVE.",SUM(".FSD_DUVES_STAIN.") AS ".FSD_DUVES_STAIN.",SUM(".FSD_DUVET_WASH_AGAIN.") AS ".FSD_DUVET_WASH_AGAIN.",SUM(".FSD_DUVE_TEAR.") AS ".FSD_DUVE_TEAR.",SUM(".FSD_DUVE_2.") AS ".FSD_DUVE_2.",SUM(".FSD_PIROCASE.") AS ".FSD_PIROCASE.",SUM(".BT.") AS ".BT.",SUM(".CT.") AS ".CT.",SUM(".FT.") AS ".FT.",SUM(".FSD_BATHROBES.") AS ".FSD_BATHROBES.",SUM(".WT.") AS ".WT.",SUM(".FSD_BASING.") AS ".FSD_BASING.",SUM(".BM.") AS ".BM.",SUM(".DT.") AS ".DT.",SUM(".FSD_NIGHTGOWN.") AS ".FSD_NIGHTGOWN.",SUM(".FSD_FSD_YUKATA.") AS ".FSD_FSD_YUKATA.",SUM(`".FSD_JINBEI_UPPER."`) AS `".FSD_JINBEI_UPPER."`,SUM(`".FSD_JINPING_BOTTOM."`) AS `".FSD_JINPING_BOTTOM."`,SUM(".FSD_AKASURI.") AS ".FSD_AKASURI.",SUM(".FSD_SOCKS.") AS ".FSD_SOCKS.",SUM(".FSD_NAPKIN_AND_OTHERS.") AS ".FSD_NAPKIN_AND_OTHERS.",SUM(".FSD_TD_CROSS_2.") AS ".FSD_TD_CROSS_2.",SUM(".FSD_SHORT_SCALE_2.") AS ".FSD_SHORT_SCALE_2.",SUM(".FSD_SHORT_STUBBLE_2.") AS ".FSD_SHORT_STUBBLE_2.",SUM(".FSD_SHORT_SCALE_OTHER_WASH_2.") AS ".FSD_SHORT_SCALE_OTHER_WASH_2.",SUM(".FSD_SHORT_SCALE_OTHER_CRACK_2.") AS ".FSD_SHORT_SCALE_OTHER_CRACK_2.",SUM(".FSD_OTHERS.") AS ".FSD_OTHERS.",SUM(".FSD_LONG_LENGTH_STAIN_2.") AS ".FSD_LONG_LENGTH_STAIN_2.",SUM(".FSD_LONG_LENGTH_WASH_AGAIN_2.") AS ".FSD_LONG_LENGTH_WASH_AGAIN_2.",SUM(".FSD_LONG_RAKE_OTHER_TEAR_2.") AS ".FSD_LONG_RAKE_OTHER_TEAR_2.",SUM(".FSD_POLYCLOTH_2.") AS ".FSD_POLYCLOTH_2.",SUM(".FSD_WHITE_COAT.") AS ".FSD_WHITE_COAT.",SUM(".FSD_PANTS.") AS ".FSD_PANTS.",SUM(".FSD_HAT.") AS ".FSD_HAT.",SUM(".FSD_ONE_PIECE.") AS ".FSD_ONE_PIECE.",SUM(".FSD_FRONT_HANGING.") AS ".FSD_FRONT_HANGING.",SUM(".FSD_TRIANGULAR_CLOTH.") AS ".FSD_TRIANGULAR_CLOTH.",SUM(".FSD_APRON.") AS ".FSD_APRON.",SUM(".FSD_SLIPPER.") AS ".FSD_SLIPPER.",SUM(".FSD_STAR_PHARMACEUTICAL.") AS ".FSD_STAR_PHARMACEUTICAL);
		$this->db->where(
			array(
				FSD_DATE.">=" =>$date_from." 00:00:00",
				FSD_DATE."<=" =>$date_to." 23:59:59"
			)
		);
		$result = $this->db->get(FINISHING_SITUATION_DATA)->result_array();
		if($result != NULL){
			$result = $result[0];
		}
		return $result;*/
		$this->db->select(PRODUCT_TOWEL.".".PT_PRODUCT_CODE.",".PT_PRODUCT_NAME.",SUM(".PT_PRODUCT_WEIGHT."*".PRT_NUMBER_RESULT.") AS total");
		$this->db->join(PRODUCT_TOWEL,PRODUCT_TOWEL.".".PT_PRODUCT_CODE."=".PRODUCTION_RESULT_TOWEL.".".PRT_PRODUCT_CODE);
		$this->db->group_by(PRODUCT_TOWEL.".".PT_PRODUCT_CODE.",".PT_PRODUCT_NAME);
		return $this->db->get(PRODUCTION_RESULT_TOWEL)->result_array();
	}
}